### ISSUE TITLE
4.x delete script fails to delete cloudformation due to route53 hostedzone

### ISSUE THREAD

**Issue by kaovilai** [konveyor/mig-agnosticd#188]
hostedzone is unable to delete due to existing A records leftover from openshift-install

`A` records leftover are of this record name pattern
- api.cluster-guid.guid.base_domain
  - elb with tag `uuid: <guid>`
- *.apps.cluster-guid.guid.base_domain
  - elb with tag  `kubernetes.io/cluster/<cluster-name>: owned` 

where `<cluster-name>` is of pattern `cluster-<shortened-guid>-<5-alphanumerics>`
where `<shortened-guid>` is leftmost 13 characters from `<guid>`

**Comment by kaovilai** [comment]
can be fixed by deleting records in the hostedzone prior to deleting cloudformation stack.
blocked by 
- https://github.com/ansible-collections/community.aws/issues/798

**Comment by markuman** [comment]
As a workaround, you can iterate over all records via `route53_info`

```yml
    - name: grab zone id
      community.aws.route53_zone:
        zone: xn--mitlinuxwrdasnichtpassiert-ohc.de
      register: AWSINFO

    - name: grab Route53 record information
      community.aws.route53_info:
        query: record_sets
        hosted_zone_id: "{{ AWSINFO.zone_id }}"
      register: RECORDS

    - debug:
        var: RECORDS
```

and delete all records or just filter them ...  
maybe this helps until the bug is fixed.

**Comment by markuman** [comment]
Because of the next related bug you'll hit, here comes the next workaround :)
When you're iterating over `RECORDS.ResourceRecordSets`, you can keep all properties.

```yml
    - name: remove all records
      community.aws.route53:
        state: absent
        hosted_zone_id: "{{ zone_id }}"
        record: "{{ item.Name }}"
        type: "{{ item.Type }}"
        value: "{{ item.ResourceRecords |  map(attribute='Value') | list }}"
        ttl: "{{ item.TTL }}"
        overwrite: yes
      with_items: "{{ RECORDS.ResourceRecordSets }}"
```

This works for all non alias records.  
When you also have alias records, you must exclude then with `when: when: item.AliasTarget is not defined` and run a 2nd task where you just delete the alias records.
